In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('walmart-products.csv')
df.head()

,timestamp,url,final_price,sku,currency,gtin,specifications,image_urls,top_reviews,rating_stars,...,sizes,colors,seller,other_attributes,customer_reviews,ingredients,initial_price,discount,ingredients_full,categories
0,2024-08-24 00:00:00.000,https://www.walmart.com/ip/Laura-Mercier-Cavia...,22.90,173530386,USD,7.361501e+11,"[{""name"":""Brand"",""value"":""Laura Mercier""},{""na...","[""https://i5.walmartimages.com/seo/Laura-Merci...","{""negative"":{},""positive"":{}}","{""five_stars"":2,""four_stars"":3,""two_stars"":1}",...,[],"[""Sugar Frost"",""Tuxedo""]",Wal███t.c███,"[{""name"":""Instructions"",""value"":""Apply directl...","[{""name"":""Jac███"",""rating"":5,""review"":""My only...","Cyclopentasiloxane, trimethylsiloxysilicate, s...",NaN,NaN,"[{""type"":""Ingredients"",""values"":""Cyclopentasil...","[""Beauty"",""Makeup"",""Eye Makeup"",""Eye Shadow"",""..."
1,2024-08-24 00:00:00.000,https://www.walmart.com/ip/Exultantex-Grey-Bla...,47.88,430528189,USD,7.710779e+11,"[{""name"":""Brand"",""value"":""Exultantex""},{""name""...","[""https://i5.walmartimages.com/seo/Exultantex-...","{""negative"":{""rating"":1,""review"":""Color not ac...","{""five_stars"":47,""four_stars"":4,""one_star"":4,""...",...,"[""50\"" x 54\"""",""50\"" x 63\"""",""50\"" x 84\"""",""50...","[""Black"",""Blue"",""Green"",""Gray"",""Natural(Ivory)...",Exu███nte███ome███,"[{""name"":""Fabric Care Instructions"",""value"":""M...","[{""name"":""Dana"",""rating"":5,""review"":""I love th...",NaN,70.80,$22.92,NaN,"[""Home"",""Decor"",""Curtains & Window Treatments""..."
2,2024-08-24 00:00:00.000,https://www.walmart.com/ip/Jessica-London-Wome...,33.24,6013308220,USD,4.651920e+11,"[{""name"":""Features"",""value"":""Easy Care""},{""nam...","[""https://i5.walmartimages.com/seo/Jessica-Lon...","{""negative"":{},""positive"":{}}","{""five_stars"":2}",...,"[""S"",""M"",""L"",""1X"",""2X"",""3X""]","[""Aqua Sea"",""Dark Olive Green"",""Dark Sapphire""...",Ful███aut███ran███,"[{""name"":""Fabric Care Instructions"",""value"":""M...","[{""name"":""Bev███y F███"",""rating"":5,""review"":""V...",NaN,37.99,$4.75,NaN,"[""Clothing"",""Womens Plus"",""Plus Size Tops"",""Pl..."
3,2024-08-24 00:00:00.000,https://www.walmart.com/ip/100-Cotton-King-Per...,49.99,161657830,USD,8.407081e+11,"[{""name"":""Brand"",""value"":""Simply Put""},{""name""...","[""https://i5.walmartimages.com/asr/d88fe658-b9...","{""negative"":{""rating"":1,""review"":""[This review...","{""five_stars"":78,""four_stars"":17,""one_star"":2,...",...,"[""Queen"",""King""]","[""Beige"",""Blue"",""Gray"",""Spa Blue""]",IC ███bal███c,"[{""name"":""Fabric Care Instructions"",""value"":""M...","[{""name"":""Jes███oge███"",""rating"":5,""review"":""[...",NaN,71.99,$22.00,NaN,"[""Home"",""Bedding"",""Duvet Covers"",""King Duvet C..."
4,2024-08-25 00:00:00.000,https://www.walmart.com/ip/Disney-Boys-Graphic...,12.99,5397071399,USD,4.600086e+11,"[{""name"":""Country of Origin - Textiles"",""value...","[""https://i5.walmartimages.com/seo/Disney-Boys...","{""negative"":{""rating"":1,""review"":""This size sh...","{""five_stars"":12,""one_star"":1,""three_stars"":1,...",...,"[""2T"",""3T"",""3T-4T"",""3-4 Years"",""4-5 Years"",""4-...","[""1#Yellow Micky"",""2#Pink Minnie"",""3#Blue Dona...",Pat███,NaN,"[{""name"":""Mary"",""rating"":5,""review"":""Love thes...",NaN,29.00,$16.01,NaN,"[""Clothing"",""Kids Clothing"",""Boys Clothing"",""B..."

In [3]:
df1 = df[['product_id',
'product_name',
'brand',
'final_price',
'currency',
'rating',
'review_count', 
'discount',
'initial_price',
'category_name',
'description',
'specifications',
'top_reviews',
'customer_reviews',
'tags',
'ingredients',
'categories']]

In [4]:
df1.head()

,product_id,product_name,brand,final_price,currency,rating,review_count,discount,initial_price,category_name,description,specifications,top_reviews,customer_reviews,tags,ingredients,categories
0,173530386,Laura Mercier Caviar Stick Eye Color Sugar Fro...,Laura Mercier,22.90,USD,4.0,6,NaN,NaN,Eye Shadow Stick,Laura Mercier Caviar Stick Eye Color Sugar Fro...,"[{""name"":""Brand"",""value"":""Laura Mercier""},{""na...","{""negative"":{},""positive"":{}}","[{""name"":""Jac███"",""rating"":5,""review"":""My only...","[""Reviewers highlighted: ease of use, blending...","Cyclopentasiloxane, trimethylsiloxysilicate, s...","[""Beauty"",""Makeup"",""Eye Makeup"",""Eye Shadow"",""..."
1,430528189,Exultantex Grey Blackout Curtains for Living R...,Exultantex,47.88,USD,4.6,58,$22.92,70.80,Blackout Curtains,✨Soft triple weave fabric with a velvet-lik...,"[{""name"":""Brand"",""value"":""Exultantex""},{""name""...","{""negative"":{""rating"":1,""review"":""Color not ac...","[{""name"":""Dana"",""rating"":5,""review"":""I love th...","[""Reduced price""]",NaN,"[""Home"",""Decor"",""Curtains & Window Treatments""..."
2,6013308220,Jessica London Women's Plus Size Stretch Knit ...,Jessica London,33.24,USD,5.0,2,$4.75,37.99,Plus Size Tops,Jessica London Women's Plus Size Stretch Knit ...,"[{""name"":""Features"",""value"":""Easy Care""},{""nam...","{""negative"":{},""positive"":{}}","[{""name"":""Bev███y F███"",""rating"":5,""review"":""V...","[""Reduced price""]",NaN,"[""Clothing"",""Womens Plus"",""Plus Size Tops"",""Pl..."
3,161657830,100% Cotton King Percale Duvet Set (3 Piece) B...,Simply Put,49.99,USD,4.7,101,$22.00,71.99,King Duvet Covers,"Inspired by decorative blue and white tiles, t...","[{""name"":""Brand"",""value"":""Simply Put""},{""name""...","{""negative"":{""rating"":1,""review"":""[This review...","[{""name"":""Jes███oge███"",""rating"":5,""review"":""[...","[""Reduced price""]",NaN,"[""Home"",""Bedding"",""Duvet Covers"",""King Duvet C..."
4,5397071399,Disney Boys Graphic Tee Donald Duck Short Slee...,Disney,12.99,USD,4.4,15,$16.01,29.00,Boys Outfit Sets,"Disney Toddler Boys Girls Graphic Tee, this...","[{""name"":""Country of Origin - Textiles"",""value...","{""negative"":{""rating"":1,""review"":""This size sh...","[{""name"":""Mary"",""rating"":5,""review"":""Love thes...","[""Best seller"",""Clearance""]",NaN,"[""Clothing"",""Kids Clothing"",""Boys Clothing"",""B..."

In [7]:
df.columns

Index(['timestamp', 'url', 'final_price', 'sku', 'currency', 'gtin',
       'specifications', 'image_urls', 'top_reviews', 'rating_stars',
       'related_pages', 'available_for_delivery', 'available_for_pickup',
       'brand', 'breadcrumbs', 'category_ids', 'review_count', 'description',
       'product_id', 'product_name', 'review_tags', 'category_url',
       'category_name', 'category_path', 'root_category_url',
       'root_category_name', 'upc', 'tags', 'main_image', 'rating',
       'unit_price', 'unit', 'aisle', 'free_returns', 'sizes', 'colors',
       'seller', 'other_attributes', 'customer_reviews', 'ingredients',
       'initial_price', 'discount', 'ingredients_full', 'categories'],
      dtype='str')

In [8]:
df1.to_csv('cleaned_data.csv',index=False)